-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/LuaNavController/LuaNavController/DetailViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-16 09:03:14 +0000



-- Objective C interface: @interface DetailViewController
local DetailViewController = objc.classInterface ("DetailViewController") --[[ @inherits UIViewController]]
